export enum DialogNames {
  PlanQualityForm = 'PlanQualityForm',
  NewProjectForm = 'NewProjectForm',
  NewJobForm = 'NewJobForm',
  RTKSettingsDialog = 'RTKSettingsDialog',
  Alert = 'Alert',
  JobInfo = 'JobInfo',
  PolygonPlanFilter = 'PolygonPlanFilter',
  SecondAntennaConfigurator = 'SecondAntennaConfigurator',
  SaveAsCustomJobType = 'SaveAsCustomJobType',
  CreateNewJobType = 'CreateNewJobType',
  LogViewer = 'LogViewer',
  ImportShapeFile = 'ImportShapeFile',
  ProcessingDialog = 'ProcessingDialog',
  UpdateDialog = 'UpdateDialog',
  UpdateAvailableDialog = 'UpdateAvailableDialog',
  CoordinateSystemInfo = 'CoordinateSystemInfo',
  ImportCoordinateSystemDialog = 'ImportCoordinateSystemDialog',
  ScannerTemperatureLegend = 'ScannerTemperatureLegend',
  ContextualHelp = 'ContextualHelp',
  LanConnectionHelp = 'LanConnectionHelp',
}
